<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>NetworkService</RootNamespace>
    <AssemblyName>NetworkService</AssemblyName>
  </PropertyGroup>

</Project>
